/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.enesfaruk.openapitutorial.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param id 
 * @param title 
 * @param body 
 */


data class GetAll200ResponseInner (

    @Json(name = "userId")
    val userId: kotlin.Int? = null,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "body")
    val body: kotlin.String? = null

)

